opt_in_rules:
    - all

disabled_rules:
    - explicit_acl # Omit ACL
    - explicit_enum_raw_value # Omit raw values if possible
    - explicit_top_level_acl # Omit ACL
    - explicit_type_interface # Omit type interface
    - indentation_width # Use Xcode indentation
    - multiline_arguments_brackets # Prioritize readability
    - multiline_parameters_brackets # Prioritize readability
    - no_extension_access_modifier # Use private extension
    - no_grouping_extension # Grouping by extension
    - prefer_nimble # Use XCTest
    - sorted_enum_cases # Prioritize readability
