on:
  workflow_dispatch:
env:
  PROJECT-NAME: Incomes
jobs:
  build:
    runs-on: macos-11
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update build number
      uses: yanamura/ios-bump-version@v1

    - name: Create commit about build number
      run: |
        git add .
        git commit -m 'Update build number'
        git push
