name: Test
on:
  pull_request:
  workflow_dispatch:
env:
  PROJECT-NAME: Incomes
jobs:
  test:
    runs-on: macos-11
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set ignored files
        run: |
          mkdir Incomes/Configuration/Package/Firebase/
          echo '${{ secrets.GOOGLESERVICE_BASE64 }}' | base64 -d -o Incomes/Configuration/Package/Firebase/GoogleService-Info.plist
          echo '${{ secrets.SECRET_BASE64 }}' | base64 -d -o Incomes/Configuration/Secret.swift
          echo '${{ secrets.STOREKIT_BASE64 }}' | base64 -d -o Incomes/Configuration/Package/StoreKit/StoreKitTestCertificate.cer

      - name: Xcode test
        run: xcodebuild -scheme ${{ env.PROJECT-NAME }} -destination "platform=iOS Simulator,name=iPhone 13 Pro" -resultBundlePath TestResults test

      - name: Test result
        uses: kishikawakatsumi/xcresulttool@v1
        if: ${{ always() }}
        with:
          path: TestResults.xcresult

      - name: Merge PR
        if: ${{ github.event.pull_request.number }}
        run: gh pr merge --merge ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
