on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo '${{ secrets.SECRET_BASE64 }}' | base64 -d -o Incomes/Configuration/Secret.swift
    - uses: yukiarrr/ios-build-action@v1.4.0
      with:
        project-path: Incomes.xcodeproj
        p12-base64: ${{ secrets.P12_BASE64 }}
        mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
        code-signing-identity: Apple Distribution
        team-id: ${{ secrets.TEAM_ID }}
    - uses: apple-actions/upload-testflight-build@v1
      with:
        app-path: 'output.ipa'
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}