on:
  pull_request:
  workflow_dispatch:
env:
  PROJECT-NAME: Incomes
jobs:
  build:
    runs-on: macos-11
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set ignored files
      run: |
        mkdir Incomes/Configuration/Package/Firebase/
        echo '${{ secrets.GOOGLESERVICE_BASE64 }}' | base64 -d -o Incomes/Configuration/Package/Firebase/GoogleService-Info.plist
        echo '${{ secrets.SECRET_BASE64 }}' | base64 -d -o Incomes/Configuration/Secret.swift
        echo '${{ secrets.STOREKIT_BASE64 }}' | base64 -d -o Incomes/Configuration/Package/StoreKit/StoreKitTestCertificate.cer

    - name: Update build number
      uses: yanamura/ios-bump-version@v1

    - name: Xcode test
      run: xcodebuild -scheme ${{ env.PROJECT-NAME }} -destination "platform=iOS Simulator,name=iPhone 13 Pro" -resultBundlePath TestResults test

    - uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: TestResults.xcresult
      if: success() || failure()

    - name: iOS build
      uses: yukiarrr/ios-build-action@v1.4.0
      with:
        project-path: ${{ env.PROJECT-NAME }}.xcodeproj
        p12-base64: ${{ secrets.P12_BASE64 }}
        mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
        code-signing-identity: Apple Distribution
        team-id: ${{ secrets.TEAM_ID }}

    - name: Upload to TestFlight
      uses: apple-actions/upload-testflight-build@v1
      with:
        app-path: 'output.ipa'
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}

    - name: Create commit about build number
      run: |
        git add .
        git commit -m 'Update build number'
        git push origin ${{ github.head_ref }}

    - name: Merge PROJECT-PATH
      if: ${{ github.event.pull_request.number }}
      run: gh pr merge ${{ github.event.pull_request.number }}
